FILM_FULL_DATA = {
    "pulp": {
        "page_ref": "pulp",
        "title": "Pulp",
        "title_original": None,
        "description": "A seedy writer of sleazy pulp novels is recruited by a quirky, reclusive ex-actor to help him write his biography at his house in Malta.",
        "image_ref": "https://a.ltrbxd.com/resized/film-poster/3/3/8/9/8/33898-pulp-0-230-0-345-crop.jpg",
        "image_ref_large": "https://a.ltrbxd.com/resized/film-poster/3/3/8/9/8/33898-pulp-0-2000-0-3000-crop.jpg",
        "banner_ref": "https://a.ltrbxd.com/resized/sm/upload/kh/4c/hf/wf/yTfJkzX7UfcAKHafIFfhidKSyJB-1920-1920-1080-1080-crop-000000.jpg?v=6badb94c4f",
        "release_year": 1972,
        "runtime": 95,
        "total_watches": 2361,
        "genres": ["Mystery", "Comedy", "Crime", "Drama"],
        "languages": [
            {"name": "English", "is_primary": True},
            {"name": "German", "is_primary": False},
            {"name": "Italian", "is_primary": False},
        ],
        "series_id": None,
        "crew": [
            {"role": "director", "ref": "mike-hodges", "name": "Mike Hodges", "rank": 1},
            {"role": "producer", "ref": "michael-klinger", "name": "Michael Klinger", "rank": 1},
            {"role": "producer", "ref": "michael-caine", "name": "Michael Caine", "rank": 2},
            {"role": "writer", "ref": "mike-hodges", "name": "Mike Hodges", "rank": 1},
            {"role": "casting", "ref": "irene-lamb", "name": "Irene Lamb", "rank": 1},
            {"role": "editor", "ref": "john-glen", "name": "John Glen", "rank": 1},
            {"role": "cinematography", "ref": "ousama-rawi", "name": "Ousama Rawi", "rank": 1},
            {"role": "assistant-director", "ref": "michael-dryhurst", "name": "Michael Dryhurst", "rank": 1},
            {"role": "camera-operator", "ref": "dusty-miller", "name": "Dusty Miller", "rank": 1},
            {"role": "production-design", "ref": "patrick-downing", "name": "Patrick Downing", "rank": 1},
            {"role": "art-direction", "ref": "darrell-lass", "name": "Darrell Lass", "rank": 1},
            {"role": "special-effects", "ref": "ron-ballanger", "name": "Ron Ballanger", "rank": 1},
            {"role": "composer", "ref": "george-martin", "name": "George Martin", "rank": 1},
            {"role": "sound", "ref": "peter-horrocks", "name": "Peter Horrocks", "rank": 1},
            {"role": "sound", "ref": "gerry-humphreys", "name": "Gerry Humphreys", "rank": 2},
            {"role": "sound", "ref": "christian-wangler", "name": "Christian Wangler", "rank": 3},
            {"role": "costume-design", "ref": "gitt-magrini", "name": "Gitt Magrini", "rank": 1},
            {"role": "makeup", "ref": "paul-engelen", "name": "Paul Engelen", "rank": 1},
            {"role": "makeup", "ref": "george-partleton", "name": "George Partleton", "rank": 2},
            {"role": "hairstyling", "ref": "mike-jones-20", "name": "Mike Jones", "rank": 1},
        ],
        "cast": [
            {"role": "actor", "ref": "michael-caine", "name": "Michael Caine", "rank": 1},
            {"role": "actor", "ref": "mickey-rooney", "name": "Mickey Rooney", "rank": 2},
            {"role": "actor", "ref": "lionel-stander", "name": "Lionel Stander", "rank": 3},
            {"role": "actor", "ref": "lizabeth-scott", "name": "Lizabeth Scott", "rank": 4},
            {"role": "actor", "ref": "nadia-cassini", "name": "Nadia Cassini", "rank": 5},
            {"role": "actor", "ref": "dennis-price", "name": "Dennis Price", "rank": 6},
            {"role": "actor", "ref": "al-lettieri", "name": "Al Lettieri", "rank": 7},
            {"role": "actor", "ref": "leopoldo-trieste", "name": "Leopoldo Trieste", "rank": 8},
            {"role": "actor", "ref": "amerigo-tot", "name": "Amerigo Tot", "rank": 9},
            {"role": "actor", "ref": "robert-sacchi", "name": "Robert Sacchi", "rank": 10},
            {"role": "actor", "ref": "giulio-donnini", "name": "Giulio Donnini", "rank": 11},
            {"role": "actor", "ref": "luciano-pigozzi", "name": "Luciano Pigozzi", "rank": 12},
            {"role": "actor", "ref": "maria-cumani-quasimodo", "name": "Maria Cumani Quasimodo", "rank": 13},
            {"role": "actor", "ref": "liu-bosisio", "name": "Liù Bosisio", "rank": 14},
            {"role": "actor", "ref": "cristina-gaioni", "name": "Cristina Gaïoni", "rank": 15},
            {"role": "actor", "ref": "janet-agren", "name": "Janet Ågren", "rank": 16},
            {"role": "actor", "ref": "irene-sophie-opperman", "name": "Irene Sophie Opperman", "rank": 17},
            {"role": "actor", "ref": "iver-gilborn", "name": "Iver Gilborn", "rank": 18},
            {"role": "actor", "ref": "elaine-olcott", "name": "Elaine Olcott", "rank": 19},
            {"role": "actor", "ref": "ave-ninchi", "name": "Ave Ninchi", "rank": 20},
            {"role": "actor", "ref": "ermelinda-de-felice", "name": "Ermelinda De Felice", "rank": 21},
            {"role": "actor", "ref": "werner-hasselmann", "name": "Werner Hasselmann", "rank": 22},
            {"role": "actor", "ref": "louise-lambert", "name": "Louise Lambert", "rank": 23},
            {"role": "actor", "ref": "victor-mercieca", "name": "Victor Mercieca", "rank": 24},
            {"role": "actor", "ref": "cettina-borg-olivier", "name": "Cettina Borg Olivier", "rank": 25},
            {"role": "actor", "ref": "joe-zammit-cordina", "name": "Joe Zammit Cordina", "rank": 26},
        ],
        "imdb_ref": "tt0069134",
        "avg_rating": 3.06,
    },
    "the-rabbis-cat": {
        "page_ref": "the-rabbis-cat",
        "title": "The Rabbi's Cat",
        "title_original": " Le Chat du rabbin ",
        "description": "The story of a rabbi and his talking cat, a sharp-tongued feline philosopher brimming with scathing humor and a less than pure love for the rabbi's teenage daughter.",
        "image_ref": "https://a.ltrbxd.com/resized/film-poster/6/1/5/4/9/61549-the-rabbi-s-cat-0-230-0-345-crop.jpg",
        "image_ref_large": "https://a.ltrbxd.com/resized/film-poster/6/1/5/4/9/61549-the-rabbi-s-cat-0-2000-0-3000-crop.jpg",
        "banner_ref": "https://a.ltrbxd.com/resized/sm/upload/ys/hy/7n/lm/obtBUwnhRO8qcjCSB9iGvN9CCWz-1920-1920-1080-1080-crop-000000.jpg?v=bbb193d6f4",
        "release_year": 2011,
        "runtime": 100,
        "total_watches": 8211,
        "genres": ["Animation", "Comedy"],
        "languages": [{"name": "French", "is_primary": True}],
        "series_id": None,
        "crew": [
            {"role": "director", "ref": "antoine-delesvaux", "name": "Antoine Delesvaux", "rank": 1},
            {"role": "director", "ref": "joann-sfar", "name": "Joann Sfar", "rank": 2},
            {"role": "producer", "ref": "antoine-delesvaux", "name": "Antoine Delesvaux", "rank": 1},
            {"role": "producer", "ref": "clement-oubrerie", "name": "Clement Oubrerie", "rank": 2},
            {"role": "producer", "ref": "joann-sfar", "name": "Joann Sfar", "rank": 3},
            {"role": "writer", "ref": "joann-sfar", "name": "Joann Sfar", "rank": 1},
            {"role": "writer", "ref": "sandrina-jardel", "name": "Sandrina Jardel", "rank": 2},
            {"role": "casting", "ref": "stephane-batut", "name": "Stéphane Batut", "rank": 1},
            {"role": "editor", "ref": "maryline-monthieux", "name": "Maryline Monthieux", "rank": 1},
            {"role": "cinematography", "ref": "jerome-brezillon", "name": "Jérôme Brézillon", "rank": 1},
            {"role": "production-design", "ref": "patrice-szweczyk", "name": "Patrice Szweczyk", "rank": 1},
            {"role": "composer", "ref": "olivier-daviaud", "name": "Olivier Daviaud", "rank": 1},
        ],
        "cast": [
            {"role": "actor", "ref": "francois-morel", "name": "François Morel", "rank": 1},
            {"role": "actor", "ref": "hafsia-herzi", "name": "Hafsia Herzi", "rank": 2},
            {"role": "actor", "ref": "maurice-benichou", "name": "Maurice Bénichou", "rank": 3},
            {"role": "actor", "ref": "jean-pierre-kalfon", "name": "Jean-Pierre Kalfon", "rank": 4},
            {"role": "actor", "ref": "daniel-cohen-1", "name": "Daniel Cohen", "rank": 5},
            {"role": "actor", "ref": "francois-damiens", "name": "François Damiens", "rank": 6},
            {"role": "actor", "ref": "mohamed-fellag", "name": "Mohamed Fellag", "rank": 7},
            {"role": "actor", "ref": "mathieu-amalric", "name": "Mathieu Amalric", "rank": 8},
            {"role": "actor", "ref": "eric-elmosnino", "name": "Éric Elmosnino", "rank": 9},
            {"role": "actor", "ref": "marguerite-abouet", "name": "Marguerite Abouet", "rank": 10},
            {"role": "actor", "ref": "wojciech-pszoniak", "name": "Wojciech Pszoniak", "rank": 11},
            {"role": "actor", "ref": "alice-houri", "name": "Alice Houri", "rank": 12},
            {"role": "actor", "ref": "sava-lolov", "name": "Sava Lolov", "rank": 13},
            {"role": "actor", "ref": "joann-sfar", "name": "Joann Sfar", "rank": 14},
        ],
        "imdb_ref": "tt1355638",
        "avg_rating": 3.8,
    },
    "a-serious-man" : { 'page_ref': 'a-serious-man',
                       'title': 'A Serious Man',
                       'title_original': None,
                       'description': 'It is 1967, and Larry Gopnik, a physics professor at a quiet Midwestern university, has just been informed by his wife Judith that she is leaving him. She has fallen in love with one of his more pompous acquaintances Sy Ableman.',
                       'image_ref': 'https://a.ltrbxd.com/resized/sm/upload/2u/48/o1/04/kCl9WXR7LOqDTEU3XUX8ssUETQR-0-230-0-345-crop.jpg',
                       'image_ref_large': 'https://a.ltrbxd.com/resized/sm/upload/2u/48/o1/04/kCl9WXR7LOqDTEU3XUX8ssUETQR-0-2000-0-3000-crop.jpg',
                       'banner_ref': 'https://a.ltrbxd.com/resized/sm/upload/xv/0b/1s/p5/a-serious-man-40-1200-1200-675-675-crop-000000.jpg?v=8d5149cfcc',
                       'release_year': 2009,
                       'runtime': 106,
                       'total_watches': 211660,
                       'genres': ['Comedy', 'Drama'],
                       'languages': [{'name': 'English', 'is_primary': True},
                                        {'name': 'Hebrew (modern)', 'is_primary': False},
                                     {'name': 'Yiddish', 'is_primary': False},
                                     {'name': 'Italian', 'is_primary': False}],
                       'series_id': None,
                       'crew': [{'role': 'director', 'ref': 'joel-coen', 'name': 'Joel Coen', 'rank': 1},
                                {'role': 'director', 'ref': 'ethan-coen', 'name': 'Ethan Coen', 'rank': 2},
                                {'role': 'producer', 'ref': 'joel-coen', 'name': 'Joel Coen', 'rank': 1},
                                {'role': 'producer', 'ref': 'ethan-coen', 'name': 'Ethan Coen', 'rank': 2},
                                {'role': 'writer', 'ref': 'joel-coen', 'name': 'Joel Coen', 'rank': 1},
                                {'role': 'writer', 'ref': 'ethan-coen', 'name': 'Ethan Coen', 'rank': 2},
                                {'role': 'casting', 'ref': 'ellen-chenoweth', 'name': 'Ellen Chenoweth', 'rank': 1}, {'role': 'casting', 'ref': 'rachel-tenner', 'name': 'Rachel Tenner', 'rank': 2}, {'role': 'casting', 'ref': 'amelia-rasche-mccarthy', 'name': 'Amelia Rasche McCarthy', 'rank': 3}, {'role': 'editor', 'ref': 'joel-coen', 'name': 'Joel Coen', 'rank': 1}, {'role': 'editor', 'ref': 'ethan-coen', 'name': 'Ethan Coen', 'rank': 2}, {'role': 'cinematography', 'ref': 'roger-deakins', 'name': 'Roger Deakins', 'rank': 1}, {'role': 'assistant-director', 'ref': 'bac-delorme', 'name': 'Bac DeLorme', 'rank': 1}, {'role': 'assistant-director', 'ref': 'betsy-magruder', 'name': 'Betsy Magruder', 'rank': 2}, {'role': 'executive-producer', 'ref': 'eric-fellner', 'name': 'Eric Fellner', 'rank': 1}, {'role': 'executive-producer', 'ref': 'robert-graf', 'name': 'Robert Graf', 'rank': 2}, {'role': 'executive-producer', 'ref': 'tim-bevan', 'name': 'Tim Bevan', 'rank': 3}, {'role': 'lighting', 'ref': 'bill-oleary', 'name': "Bill O'Leary", 'rank': 1}, {'role': 'camera-operator', 'ref': 'roger-deakins', 'name': 'Roger Deakins', 'rank': 1}, {'role': 'production-design', 'ref': 'jess-gonchor', 'name': 'Jess Gonchor', 'rank': 1}, {'role': 'art-direction', 'ref': 'deborah-jensen-1', 'name': 'Deborah Jensen', 'rank': 1}, {'role': 'art-direction', 'ref': 'jeff-schoen', 'name': 'Jeff Schoen', 'rank': 2}, {'role': 'set-decoration', 'ref': 'nancy-haigh', 'name': 'Nancy Haigh', 'rank': 1}, {'role': 'set-decoration', 'ref': 'maria-baker', 'name': 'Maria Baker', 'rank': 2}, {'role': 'special-effects', 'ref': 'larz-anderson', 'name': 'Larz Anderson', 'rank': 1}, {'role': 'visual-effects', 'ref': 'steve-griffith', 'name': 'Steve Griffith', 'rank': 1}, {'role': 'visual-effects', 'ref': 'vincent-cirelli', 'name': 'Vincent Cirelli', 'rank': 2}, {'role': 'visual-effects', 'ref': 'steven-swanson', 'name': 'Steven Swanson', 'rank': 3}, {'role': 'title-design', 'ref': 'randall-balsmeyer', 'name': 'Randall Balsmeyer', 'rank': 1}, {'role': 'stunts', 'ref': 'jery-hewitt', 'name': 'Jery Hewitt', 'rank': 1}, {'role': 'stunts', 'ref': 'danny-downey', 'name': 'Danny Downey', 'rank': 2}, {'role': 'stunts', 'ref': 'eric-d-howell', 'name': 'Eric D. Howell', 'rank': 3}, {'role': 'composer', 'ref': 'carter-burwell', 'name': 'Carter Burwell', 'rank': 1}, {'role': 'sound', 'ref': 'skip-lievsay', 'name': 'Skip Lievsay', 'rank': 1}, {'role': 'sound', 'ref': 'craig-berkey', 'name': 'Craig Berkey', 'rank': 2}, {'role': 'sound', 'ref': 'greg-orloff', 'name': 'Greg Orloff', 'rank': 3}, {'role': 'sound', 'ref': 'joel-dougherty', 'name': 'Joel Dougherty', 'rank': 4}, {'role': 'sound', 'ref': 'marko-costanzo', 'name': 'Marko Costanzo', 'rank': 5}, {'role': 'sound', 'ref': 'george-a-lara', 'name': 'George A. Lara', 'rank': 6}, {'role': 'sound', 'ref': 'peter-kurland', 'name': 'Peter Kurland', 'rank': 7}, {'role': 'costume-design', 'ref': 'mary-zophres', 'name': 'Mary Zophres', 'rank': 1}, {'role': 'makeup', 'ref': 'jean-ann-black', 'name': 'Jean Ann Black', 'rank': 1}, {'role': 'makeup', 'ref': 'mary-flaa', 'name': 'Mary Flaa', 'rank': 2}, {'role': 'makeup', 'ref': 'christien-tinsley', 'name': 'Christien Tinsley', 'rank': 3}, {'role': 'hairstyling', 'ref': 'fria-aradottir', 'name': 'Fríða Aradóttir', 'rank': 1}], 'cast': [{'role': 'actor', 'ref': 'michael-stuhlbarg', 'name': 'Michael Stuhlbarg', 'rank': 1}, {'role': 'actor', 'ref': 'richard-kind', 'name': 'Richard Kind', 'rank': 2}, {'role': 'actor', 'ref': 'fred-melamed', 'name': 'Fred Melamed', 'rank': 3}, {'role': 'actor', 'ref': 'sari-lennick', 'name': 'Sari Lennick', 'rank': 4}, {'role': 'actor', 'ref': 'aaron-wolff', 'name': 'Aaron Wolff', 'rank': 5}, {'role': 'actor', 'ref': 'jessica-mcmanus', 'name': 'Jessica McManus', 'rank': 6}, {'role': 'actor', 'ref': 'peter-breitmayer', 'name': 'Peter Breitmayer', 'rank': 7}, {'role': 'actor', 'ref': 'brent-braunschweig', 'name': 'Brent Braunschweig', 'rank': 8}, {'role': 'actor', 'ref': 'david-kang', 'name': 'David Kang', 'rank': 9}, {'role': 'actor', 'ref': 'benjamin-portnoe', 'name': 'Benjamin Portnoe', 'rank': 10}, {'role': 'actor', 'ref': 'jack-swiler', 'name': 'Jack Swiler', 'rank': 11}, {'role': 'actor', 'ref': 'andrew-s-lentz', 'name': 'Andrew S. Lentz', 'rank': 12}, {'role': 'actor', 'ref': 'jon-kaminski-jr', 'name': 'Jon Kaminski Jr.', 'rank': 13}, {'role': 'actor', 'ref': 'ari-hoptman', 'name': 'Ari Hoptman', 'rank': 14}, {'role': 'actor', 'ref': 'alan-mandell', 'name': 'Alan Mandell', 'rank': 15}, {'role': 'actor', 'ref': 'amy-landecker', 'name': 'Amy Landecker', 'rank': 16}, {'role': 'actor', 'ref': 'george-wyner', 'name': 'George Wyner', 'rank': 17}, {'role': 'actor', 'ref': 'michael-tezla', 'name': 'Michael Tezla', 'rank': 18}, {'role': 'actor', 'ref': 'katherine-borowitz', 'name': 'Katherine Borowitz', 'rank': 19}, {'role': 'actor', 'ref': 'stephen-park-1', 'name': 'Steve Park', 'rank': 20}, {'role': 'actor', 'ref': 'allen-lewis-rickman', 'name': 'Allen Lewis Rickman', 'rank': 21}, {'role': 'actor', 'ref': 'yelena-shmulenson', 'name': 'Yelena Shmulenson', 'rank': 22}, {'role': 'actor', 'ref': 'fyvush-finkel', 'name': 'Fyvush Finkel', 'rank': 23}, {'role': 'actor', 'ref': 'ronald-schultz', 'name': 'Ronald Schultz', 'rank': 24}, {'role': 'actor', 'ref': 'raye-birk', 'name': 'Raye Birk', 'rank': 25}, {'role': 'actor', 'ref': 'jane-hammill', 'name': 'Jane Hammill', 'rank': 26}, {'role': 'actor', 'ref': 'claudia-wilkens', 'name': 'Claudia Wilkens', 'rank': 27}, {'role': 'actor', 'ref': 'simon-helberg', 'name': 'Simon Helberg', 'rank': 28}, {'role': 'actor', 'ref': 'adam-arkin-1', 'name': 'Adam Arkin', 'rank': 29}, {'role': 'actor', 'ref': 'james-cada', 'name': 'James Cada', 'rank': 30}, {'role': 'actor', 'ref': 'michael-lerner', 'name': 'Michael Lerner', 'rank': 31}, {'role': 'actor', 'ref': 'charles-brin', 'name': 'Charles Brin', 'rank': 32}, {'role': 'actor', 'ref': 'michael-engel-3', 'name': 'Michael Engel', 'rank': 33}, {'role': 'actor', 'ref': 'tyson-bidner', 'name': 'Tyson Bidner', 'rank': 34}, {'role': 'actor', 'ref': 'phyllis-harris', 'name': 'Phyllis Harris', 'rank': 35}, {'role': 'actor', 'ref': 'piper-sigel-bruse', 'name': 'Piper Sigel-Bruse', 'rank': 36}, {'role': 'actor', 'ref': 'hannah-nemer', 'name': 'Hannah Nemer', 'rank': 37}, {'role': 'actor', 'ref': 'rita-vassallo', 'name': 'Rita Vassallo', 'rank': 38}, {'role': 'actor', 'ref': 'warren-keith-1', 'name': 'Warren Keith', 'rank': 39}, {'role': 'actor', 'ref': 'neil-newman', 'name': 'Neil Newman', 'rank': 40}, {'role': 'actor', 'ref': 'tim-russell', 'name': 'Tim Russell', 'rank': 41}, {'role': 'actor', 'ref': 'jim-lichtscheidl', 'name': 'Jim Lichtscheidl', 'rank': 42}, {'role': 'actor', 'ref': 'wayne-a-evenson', 'name': 'Wayne A. Evenson', 'rank': 43}, {'role': 'actor', 'ref': 'scott-thompson-baker', 'name': 'Scott Thompson Baker', 'rank': 44}, {'role': 'actor', 'ref': 'landyn-banx', 'name': 'Landyn Banx', 'rank': 45}, {'role': 'actor', 'ref': 'punnavith-koy', 'name': 'Punnavith Koy', 'rank': 46}, {'role': 'actor', 'ref': 'joel-thingvall', 'name': 'Joel Thingvall', 'rank': 47}, {'role': 'actor', 'ref': 'amanda-day-1', 'name': 'Amanda Day', 'rank': 48}],
                       'imdb_ref': 'tt1019452',
                       'avg_rating': 3.87},
    'hero-2002' : { 'page_ref': 'hero-2002', 'title': 'Hero', 'title_original': ' 英雄 ', 'description': "During China's Warring States period, a district prefect arrives at the palace of Qin Shi Huang, claiming to have killed the three assassins who had made an attempt on the king's life three years ago.", 'image_ref': 'https://a.ltrbxd.com/resized/sm/upload/ox/qe/4i/v4/u1zSyesxUf1FSHV6RKQHEto5HcD-0-230-0-345-crop.jpg', 'image_ref_large': 'https://a.ltrbxd.com/resized/sm/upload/ox/qe/4i/v4/u1zSyesxUf1FSHV6RKQHEto5HcD-0-2000-0-3000-crop.jpg', 'banner_ref': 'https://a.ltrbxd.com/resized/sm/upload/fs/r4/pb/0s/hero-1920-1920-1080-1080-crop-000000.jpg?v=ea0f09443c', 'release_year': 2002, 'runtime': 99, 'total_watches': 112439, 'genres': ['Adventure', 'Drama', 'Action', 'History'], 'languages': [{'name': 'Chinese', 'is_primary': True}], 'series_id': None, 'crew': [{'role': 'director', 'ref': 'zhang-yimou', 'name': 'Zhang Yimou', 'rank': 1}, {'role': 'producer', 'ref': 'zhang-yimou', 'name': 'Zhang Yimou', 'rank': 1}, {'role': 'producer', 'ref': 'zhang-zhenyan', 'name': 'Zhang Zhenyan', 'rank': 2}, {'role': 'producer', 'ref': 'william-kong', 'name': 'Bill Kong Chi-Keung', 'rank': 3}, {'role': 'writer', 'ref': 'feng-li-4', 'name': 'Feng Li', 'rank': 1}, {'role': 'original-writer', 'ref': 'zhang-yimou', 'name': 'Zhang Yimou', 'rank': 1}, {'role': 'original-writer', 'ref': 'wang-bin-6', 'name': 'Wang Bin', 'rank': 2}, {'role': 'editor', 'ref': 'ru-zhai', 'name': 'Ru Zhai', 'rank': 1}, {'role': 'editor', 'ref': 'vincent-lee', 'name': 'Vincent Lee', 'rank': 2}, {'role': 'editor', 'ref': 'angie-lam-on-yee', 'name': 'Angie Lam On-Yee', 'rank': 3}, {'role': 'cinematography', 'ref': 'christopher-doyle', 'name': 'Christopher Doyle', 'rank': 1}, {'role': 'executive-producer', 'ref': 'shoufang-dou', 'name': 'Shoufang Dou', 'rank': 1}, {'role': 'executive-producer', 'ref': 'zhang-weiping', 'name': 'Zhang Weiping', 'rank': 2}, {'role': 'executive-producer', 'ref': 'quentin-tarantino', 'name': 'Quentin Tarantino', 'rank': 3}, {'role': 'additional-photography', 'ref': 'jasmine-yuen-carrucan', 'name': 'Jasmine Yuen Carrucan', 'rank': 1}, {'role': 'additional-photography', 'ref': 'hou-yong', 'name': 'Hou Yong', 'rank': 2}, {'role': 'production-design', 'ref': 'tingxiao-huo', 'name': 'Tingxiao Huo', 'rank': 1}, {'role': 'production-design', 'ref': 'zhenzhou-yi', 'name': 'Zhenzhou Yi', 'rank': 2}, {'role': 'stunts', 'ref': 'tony-ching-siu-tung', 'name': 'Tony Ching Siu-Tung', 'rank': 1}, {'role': 'stunts', 'ref': 'max-zhang-2', 'name': 'Max Zhang', 'rank': 2}, {'role': 'choreography', 'ref': 'jack-wong-5', 'name': 'Jack Wong', 'rank': 1}, {'role': 'choreography', 'ref': 'stephen-tung-wai', 'name': 'Stephen Tung Wai', 'rank': 2}, {'role': 'composer', 'ref': 'tan-dun-1', 'name': 'Tan Dun', 'rank': 1}, {'role': 'songs', 'ref': 'faye-wong', 'name': 'Faye Wong', 'rank': 1}, {'role': 'costume-design', 'ref': 'emi-wada', 'name': 'Emi Wada', 'rank': 1}, {'role': 'makeup', 'ref': 'ji-wei-hua', 'name': 'Ji Wei-Hua', 'rank': 1}, {'role': 'makeup', 'ref': 'yang-xiao-hai', 'name': 'Yang Xiao-Hai', 'rank': 2}, {'role': 'makeup', 'ref': 'kwan-lee-na', 'name': 'Kwan Lee-Na', 'rank': 3}, {'role': 'makeup', 'ref': 'yang-shu-dong', 'name': 'Yang Shu-Dong', 'rank': 4}], 'cast': [{'role': 'actor', 'ref': 'jet-li', 'name': 'Jet Li', 'rank': 1}, {'role': 'actor', 'ref': 'tony-leung-chiu-wai', 'name': 'Tony Leung Chiu-wai', 'rank': 2}, {'role': 'actor', 'ref': 'maggie-cheung-man-yuk-1', 'name': 'Maggie Cheung', 'rank': 3}, {'role': 'actor', 'ref': 'donnie-yen', 'name': 'Donnie Yen', 'rank': 4}, {'role': 'actor', 'ref': 'zhang-ziyi', 'name': 'Zhang Ziyi', 'rank': 5}, {'role': 'actor', 'ref': 'chen-daoming', 'name': 'Chen Daoming', 'rank': 6}, {'role': 'actor', 'ref': 'zhongyuan-liu', 'name': 'Liu Zhongyuan', 'rank': 7}, {'role': 'actor', 'ref': 'zheng-tianyong', 'name': 'Zheng Tianyong', 'rank': 8}, {'role': 'actor', 'ref': 'qin-yan', 'name': 'Qin Yan', 'rank': 9}, {'role': 'actor', 'ref': 'zhang-yakun', 'name': 'Zhang Yakun', 'rank': 10}, {'role': 'actor', 'ref': 'james-hong', 'name': 'James Hong', 'rank': 11}, {'role': 'actor', 'ref': 'chang-xiao-yang', 'name': 'Chang Xiao Yang', 'rank': 12}, {'role': 'actor', 'ref': 'jin-ming', 'name': 'Jin Ming', 'rank': 13}, {'role': 'actor', 'ref': 'ma-wen-hua', 'name': 'Ma Wen Hua', 'rank': 14}, {'role': 'actor', 'ref': 'shou-xin-wang', 'name': 'Shou Xin Wang', 'rank': 15}, {'role': 'actor', 'ref': 'xu-kuang-hua', 'name': 'Xu Kuang Hua', 'rank': 16}], 'imdb_ref': 'tt0299977', 'avg_rating': 4.0}}



