version: '3.8'

services:
  worker:
    build:
      context: ../..
      dockerfile: worker/scraper/Dockerfile
      pull: true
    image: siegf/filmdatacollector:done
    command: celery -A worker.scraper.run:app worker --beat --loglevel=debug
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
      - UPDATELOG_URL=${UPDATELOG_URL}
      - API_ADRESS=${API_ADDRESS}

    restart: unless-stopped

