version: '3.8'

services:
  worker:
    build:
      context: ..
      dockerfile: worker/Dockerfile
    image: siegf/filmdatacollector:latest
    command: celery -A worker.run:app worker --beat --loglevel=info
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
      - UPDATELOG_URL=${UPDATELOG_URL}

    restart: unless-stopped

