[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "worker"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "celery",
    "python-dotenv",
    "redis",
    "aiohttp",
    "beautifulsoup4",
    "requests",
]

[project.scripts]
enqueue = "enqueue:main"

[tool.setuptools]
packages = ["util", "dataCollectors"]
py-modules = ["enqueue","app","tasks"]